apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: insights-operator-gathering-conditions-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: insights-operator-gathering-conditions-service
    app.kubernetes.io/part-of: insights-operator-gathering-conditions-service
  name: insights-operator-gathering-conditions-service
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: insights-operator-gathering-conditions-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: insights-operator-gathering-conditions-service
    spec:
      containers:
      - image: image
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
